---
- name: install dependencies
  dnf:
    name:
      - curl
      - wget
      - tar
      - bzip2
      - gzip
      - unzip
      - python3
      - binutils
      - bc 
      - jq
      - tmux
      - glibc.i686
      - libstdc++
      - libstdc++.i686
    state: present
    update_cache: yes