---
- name: install dependencies
  dnf:
    name:
      - curl
      - wget
      - tar
      - bzip2
      - gzip
      - unzip
      - python3
      - binutils
      - bc 
      - jq
      - tmux
      - glibc.i686
      - libstdc++
      - libstdc++.i686
    state: present
    update_cache: yes

- name: create sfserver user
  user:
    create_home: yes
    name: sfserver
    state: present
- name: copy skel bash
  copy:
    src: /etc/skel/.bashrc
    dst: /home/sfserver/.bashrc
