---
- name: Get gameserver control scripts
  become: true
  become_user: '{{ lgsm_user }}'
  ansible.builtin.command: "{{ lgsm_installdir }}/{{ lgsm_installer_name }} {{ lgsm_server }}"
  args:
    chdir: "{{ lgsm_installdir }}"
    creates: "{{ lgsm_installdir }}/{{ lgsm_server }}"

- name: Install gameserver
  become: true
  become_user: '{{ lgsm_user }}'
  ansible.builtin.command: "{{ lgsm_installdir }}/{{ lgsm_server }} auto-install"
  args:
    chdir: "{{ lgsm_installdir }}"
    creates: "{{ lgsm_installdir }}/serverfiles"
  when: lgsm_install_server

- name: Create instance config file
  ansible.builtin.template:
    src: instance.cfg.j2
    dest: "{{ lgsm_server_config }}"
    mode: '0644'
    owner: "{{ lgsm_user }}"
    group: "{{ lgsm_group }}"

- name: Install gameserver systemd unit file
  ansible.builtin.template:
    src: systemd-unit.j2
    dest: "/etc/systemd/system/{{ lgsm_server }}.service"
    mode: '0644'
    owner: root
    group: root

- name: Enable and start gameserver systemd unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ lgsm_server }}"
    daemon_reload: true
