---
- hosts: factorygame
  become: true
  pre_tasks:
  - name: install epel-release
    dnf:
      name: epel-release
      state: latest
      update_cache: true
  tasks:
  - name: install dependencies
    dnf:
      name:
        - bc
        - binutils
        - bzip2
        - cpio
        - curl
        - file
        - glibc.i686
        - gzip
        - hostname
        - jq
        - libstdc++.i686
        - nmap-ncat
        - python36
        - tar
        - tmux
        - unzip
        - util-linux
        - wget
        - xz
      state: present
      update_cache: true

  - name: create sfserver user
    user:
      create_home: true
      name: sfserver
      state: present

  - name: copy skel bash
    copy:
      remote_src: true
      src: /etc/skel/.bashrc
      dest: /home/sfserver/.bashrc

  - name: create .ssh in sfserver home
    file:
      path: /home/sfserver/.ssh
      state: directory

  - name: copy authorized ssh key
    copy:
      remote_src: true
      src: /root/.ssh/authorized_keys
      dest: /home/sfserver/.ssh/authorized_keys
      owner: sfserver
      group: sfserver
