---
- hosts: valheim
  become: true
  roles:
    - ./roles/valheim
  tasks:
  - name: create vhserver user
    user:
      create_home: true
      name: vhserver
      state: present
  - name: copy .bash from skel
    copy:
      remote_src: true
      src: /etc/skel/.bashrc
      dest: /home/vhserver/.bashrc
      owner: vhserver
      group: vhserver
  - name: create .ssh directory in vhserver home
    file:
      path: /home/vhserver/.ssh
      state: directory
      owner: vhserver
      group: vhserver
  - name: copy authorized ssh key
    copy:
      remote_src: true
      src: /root/.ssh/authorized_keys
      dest: /home/vhserver/.ssh/authorized_keys
      owner: vhserver
      group: vhserver
