- name: Add 32bit package architecture.
  ansible.builtin.become: true
  ansible.builtin.command: "dpkg --add-architecture i386"
- name: Install LGSM dependencies.
  become: true
  ansible.builtin.package:
    name:
      - curl
      - wget
      - file
      - tar
      - bzip2
      - gzip
      - unzip
      - bsdmainutils
      - python3
      - util-linux
      - ca-certificates
      - binutils
      - bc
      - jq
      - tmux
      - netcat
      - lib32gcc-s1
      - lib32stdc++6
      - libsdl2-2.0-0:i386
    update_cache: true
    state: latest
