---
  - hosts: mc
    become: true
    pre_tasks: 
      - name: update package cache
        dnf: 
          update_cache: yes
          autoremove: yes
    tasks:
    - name: install base applications
      dnf:
        name: 
          - vim
          - tmux
          - python3
          - java-1.8.0-openjdk-headless
          - epel-release
        state: present
    - name: create mc user
      user:
        name: mc
        state: present
        shell: /bin/bash
        password: "{{ pwd|password_hash('sha512') }}"