---
- hosts: minecraft
  become: true
  pre_tasks:
  - name: install epel-release
    dnf:
      name: epel-release
      state: latest
      update_cache: true
  tasks:
  - name: install dependencies
    dnf:
      name:
        - bc
        - binutils
        - bzip2
        - cpio
        - curl
        - file
        - glibc.i686
        - gzip
        - hostname
        - java-11-openjdk
        - jq
        - libstdc++.i686
        - nmap-ncat
        - python3
        - tar
        - tmux
        - unzip
        - util-linux
        - wget
        - xz
      state: present
      update_cache: true
  - name: create pmcserver user
    user:
      create_home: true
      name: pmcserver
      state: present
  - name: copy .bash from skel
    copy:
      remote_src: true
      src: /etc/skel/.bashrc
      dest: /home/pmcserver/.bashrc
  - name: create .ssh directory in pmcserver home
    file:
      path: /home/pmcserver/.ssh
      state: directory
  - name: copy authorized ssh key
    copy:
      remote_src: true
      src: /root/.ssh/authorized_keys
      dest: /home/pmcserver/.ssh/authorized_keys
      owner: pmcserver
      group: pmcserver
