---
  - hosts: valheim
    become: true
    pre_tasks:
    - name: install epel-release
      dnf:
        name: epel-release
        state: latest
        update_cache: true
    tasks:
    - name: create vhserver user
      user:
        create_home: true
        name: vhserver
        state: present
    - name: copy .bash from skel
      copy:
        remote_src: true
        src: /etc/skel/.bashrc
        dest: /home/vhserver/.bashrc
        owner: vhserver
        group: vhserver
    - name: create .ssh directory in vhserver home
      file:
        path: /home/vhserver/.ssh
        state: directory
        owner: vhserver
        group: vhserver
    - name: copy authorized ssh key
      copy:
        remote_src: true
        src: /root/.ssh/authorized_keys
        dest: /home/vhserver/.ssh/authorized_keys
        owner: vhserver
        group: vhserver
    - name: install dependencies
      dnf:
        name:
        - bc
        - binutils
        - bzip2
        - cpio
        - curl
        - epel-release
        - file
        - glibc-devel
        - glibc.i686
        - gzip
        - hostname
        - jq
        - libstdc++.i686
        - nmap-ncat
        - python3
        - tar
        - tmux
        - unzip
        - util-linux
        - wget
        - xz
        state: present
