galaxy_info:
  role_name: lgsm
  author: djroot2
  description: Ansible role for Linux Game Server Mangers (LinuxGSM) install.

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - games
    - linuxgsm
    - lgsm
    - cstrike
    - csgo
    - server

dependencies: []
